apiVersion: hops.ops.com.ai/v1alpha1
kind: IstioStack
metadata:
  name: istio
  namespace: default
spec:
  clusterName: prod-cluster
  labels:
    team: platform
  namespace: istio-system
  # renovate: datasource=helm depName=base registryUrl=https://istio-release.storage.googleapis.com/charts
  chartVersion: "1.30.4"

  ingressGateway:
    enabled: true
    name: platform
    namespace: istio-ingress
    gatewayClassName: istio
    listeners:
    - name: https
      hostname: "*.example.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
      allowedRoutes:
        namespaces:
          from: All
